import json
C="https://commons.wikimedia.org/wiki/Special:FilePath/"
def img(f,credit,lic):
    return {"url":C+f.replace(' ','_')+"?width=800","credit":credit,"license":lic,"page":"https://commons.wikimedia.org/wiki/File:"+f.replace(' ','_')}
KML="Richard DeDomenici 'CROYDON REDUX' Google My Map (KML export, mid=1gqCuM1Kv3t8914BBbNlAOvKXpeAu3T2t)"
S=[
dict(id="david-lean",name="David Lean Cinema, Croydon Clocktower",address="Katharine Street, CR9 1ET",lat=51.37213,lng=-0.09901,
 films=[dict(title="Start & finish: the David Lean Cinema",year=None,type="venue",scene="Welcome to Crollywood. The tour starts and ends at the David Lean Cinema, named after Croydon-born director David Lean (Lawrence of Arabia, Brief Encounter). It's also where Heads of State: Redux premieres (14 Nov 2026).")],
 image=img("Croydon Clocktower on Katharine Street - panoramio.jpg","Panoramio user via Wikimedia Commons","CC BY-SA 3.0"),
 sources=["User brief (start/end point)","https://www.davidleancinema.org.uk/event/crollywood-tour-heads-of-state-redux-premier/","Nominatim/OSM geocode"],confidence="high",confidence_note="Venue location verified via OSM."),
dict(id="peep-show-registry",name="Former Croydon Registry Office, Mint Walk",address="Mint Walk (now Bernard Weatherill House area)",lat=51.37174,lng=-0.10002,
 films=[dict(title="Peep Show",year=2004,type="TV",scene="The registry office where Jeremy marries Nancy (so she can get a green card). Demolished to make way for the council's new headquarters.")],
 image=img("Croydon Council.JPG","A P Monblat via Wikimedia Commons (Bernard Weatherill House, built on the site)","CC BY-SA 4.0"),
 sources=[KML],confidence="medium",confidence_note="Pin and description from DeDomenici's map; building demolished so the spot is approximate."),
dict(id="konga",name="High Street, north of the Flyover",address="High Street, CR0",lat=51.37106,lng=-0.10025,
 films=[dict(title="Konga",year=1961,type="film",scene="A giant ape runs amok in 'London'. The terrified-locals crowd shots were filmed on the east side of Croydon High Street, just north of the Flyover.")],
 image=img("High Street, Croydon - geograph.org.uk - 2728006.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML,"https://movie-locations.com/movies/k/Konga.php"],confidence="high",confidence_note="Map pin plus movie-locations.com description agree."),
dict(id="matthews-yard",name="Matthews Yard",address="Matthews Yard, off Surrey Street, CR0 1FF",lat=51.37236,lng=-0.10111,
 films=[dict(title="American Assassin: Redux (Crollywood HQ)",year=2018,type="redux",scene="Start and finish of the original 2018 Crollywood tour, and the venue of the American Assassin: Redux world premiere at Matthews Yard Theatre.")],
 image=img("Matthews Yard, Croydon, CR0 (34398740191).jpg","Flickr user via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML,"http://www.justcroydon.com/events/5609/18-May-2018/culture/richard-dedomenici-american-assassin-redux"],confidence="high",confidence_note="Not a film location as such: the tour's original start point."),
dict(id="heads-of-state-overtons",name="Overton's Yard & Surrey Street car park",address="Overton's Yard, off Surrey Street, CR0 1SL",lat=51.37276,lng=-0.10186,
 films=[dict(title="Heads of State",year=2025,type="film",scene="June 2023 night shoot for the 'Warsaw' chase: action including a car crash and (silenced) explosions filmed around Overton's Yard and on the roof of the Surrey Street car park next door.")],
 image=None,
 sources=["https://insidecroydon.com/2023/06/22/idris-elba-and-film-co-stars-spotted-doing-the-st-georges-walk/","https://www.mylondon.news/news/south-london-news/idris-elba-john-cena-priyanka-27170859","Nominatim/OSM (Overton's Yard)"],confidence="medium",confidence_note="Local press reports filming here; exact on-screen shots not frame-matched. Car-park rooftop pin is approximate."),
dict(id="peep-show-loop-bar",name="Loop Bar, Crown Hill",address="Crown Hill, CR0",lat=51.37374,lng=-0.10120,
 films=[dict(title="Peep Show",year=2003,type="TV",scene="The bar ('Shooshh') where Mark plays pool (badly) with his nemesis Jeff.")],
 image=img("Crown Hill, Croydon - geograph.org.uk - 6180140.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML],confidence="medium",confidence_note="From DeDomenici's map; venue may have changed name."),
dict(id="it-crowd",name="Whitgift Centre, North End entrance",address="North End, CR0",lat=51.37601,lng=-0.10125,
 films=[dict(title="The IT Crowd",year=2010,type="TV",scene="Series 4 'Bad Boys': Moss shoplifts copies of Grand Designs magazine while he and Roy are bunking off.")],
 image=img("Whitgift Centre - North End entrance.jpg","Hzh via Wikimedia Commons","CC BY-SA 4.0"),
 sources=[KML,"https://moviemaps.org/locations/279 (nearby: Whitgift Shopping Centre, The IT Crowd)"],confidence="high",confidence_note="Two sources agree on the Whitgift Centre; the shop's exact unit isn't confirmed."),
dict(id="opalite",name="Whitgift Centre: the 'Opalite' escalator",address="Whitgift Centre, enter from North End",lat=51.37580,lng=-0.10010,
 films=[dict(title="Taylor Swift – 'Opalite' (music video)",year=2026,type="music video",scene="Taylor Swift and Domhnall Gleeson ride down the escalator and into a shop where Graham Norton hands out samples of 'Opalite' cleaning spray. Shot in November 2025 and released 6 Feb 2026. Fans now take selfies on the escalator opposite Clarks.")],
 image=img("The Whitgift Centre, Croydon - geograph.org.uk - 694473.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=["https://www.standard.co.uk/showbiz/taylor-swift-fans-whitgift-shopping-centre-croydon-opalite-music-video-b1270477.html","https://www.bbc.co.uk/newsround/articles/cn71xpv77zlo","https://metro.co.uk/2026/02/10/im-a-swiftie-this-flocking-a-luck-croydon-shopping-centre-26815066/","https://londonist.com/london/features/whitgift-centre-escalator-taylor-swift"],
 confidence="high",confidence_note="Whitgift Centre is confirmed by several outlets. The pin is approximate: it marks the escalator opposite Clarks, reached from North End, inside the mall, and needs checking on site."),
dict(id="terry-and-june",name="Whitgift Centre, Wellesley Road side",address="Wellesley Road, CR0",lat=51.37671,lng=-0.09954,
 films=[dict(title="Terry & June",year=1979,type="TV",scene="The sitcom was set in Purley, and its opening titles were filmed around the Whitgift Centre and Fairfield Halls area.")],
 image=img("Whitgift Centre, Croydon, 1976.jpg","John Shepherd via Wikimedia Commons","CC BY 2.0"),
 sources=[KML,"https://en-academic.com/dic.nsf/enwiki/273044 (Croydon article mirror)"],confidence="low",confidence_note="Map pin with no description. The title-sequence claim comes from a single secondary source."),
dict(id="dark-knight-rises",name="Delta Point, Wellesley Road",address="35 Wellesley Road (by West Croydon station)",lat=51.37907,lng=-0.10047,
 films=[dict(title="The Dark Knight Rises",year=2012,type="film",scene="Played Gotham General Hospital: Blake rushes in to save Commissioner Gordon from Bane's thugs, and a masked Bruce Wayne visits Gordon. Now converted to flats.")],
 image=img("Delta Point, Wellesley Road, Croydon - geograph.org.uk - 1629615.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML,"https://movie-locations.com/movies/d/Dark-Knight-Rises.php","https://www.yourlocalguardian.co.uk/news/9033781.building-facing-destruction-as-new-batman-filmed-in-croydon/"],confidence="high",confidence_note="Several sources agree. The KML pin was about 60m south, so this uses the OSM building position."),
dict(id="peep-show-canterbury",name="Canterbury House, Sydenham Road",address="Sydenham Road, CR0",lat=51.37764,lng=-0.09755,
 films=[dict(title="Peep Show",year=2003,type="TV",scene="The JLB Credit office where Mark and Sophie first met. It's being converted to flats, so the interior they filmed in is gone.")],
 image=img("Canterbury House, Sydenham Road - geograph.org.uk - 2251638.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML,"Nominatim/OSM"],confidence="high",confidence_note="Detailed description on the map, and the building is verified in OSM."),
dict(id="man-who-knew-too-little",name="Dingwall Road / Lansdowne Road roundabout",address="Dingwall Road, CR0",lat=51.37694,lng=-0.09555,
 films=[dict(title="The Man Who Knew Too Little",year=1997,type="film",scene="Bill Murray's car-chase roundabout scene, with Lansdowne Road and Corinthian House in shot. The chase also uses the Croydon Flyover.")],
 image=img("Dingwall Road, Croydon - geograph.org.uk - 475506.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML,"https://londononlocation.co.uk/films/man-who-knew-too-little-the/"],confidence="high",confidence_note="Map pin and London on Location agree."),
dict(id="velvet-goldmine",name="Wellesley Road (looking north)",address="Wellesley Road, CR0",lat=51.37564,lng=-0.09802,
 films=[dict(title="Velvet Goldmine",year=1998,type="film",scene="Croydon stands in for 1980s New York. The 'nightmarish' street scene looks north along Wellesley Road as Christian Bale's journalist Arthur moves through town.")],
 image=None,
 sources=[KML,"https://londononlocation.co.uk/films/velvet-goldmine/"],confidence="medium",confidence_note="The street is confirmed, but the exact camera position is approximate."),
dict(id="criminal-bourne",name="College Green: the old School of Art (Segas House)",address="College Green / Park Lane, CR0",lat=51.37303,lng=-0.09602,
 films=[dict(title="Jason Bourne",year=2016,type="film",scene="The old Croydon School of Art's photographic studio doubles as a Berlin warehouse for a Matt Damon fight scene, while the CIA watches the windows."),
        dict(title="Criminal",year=2016,type="film",scene="Croydon College became CIA HQ, a lab and a fugitive's hideout. There's a shoot-out on College Road, George Street and Dingwall Road, and a night scene in the Park Lane underpass.")],
 image=img("CroydonCollege.jpg","CroydonCollege via Wikimedia Commons","CC BY-SA 3.0"),
 sources=[KML,"https://www.movie-locations.com/movies/j/Jason-Bourne.php","https://croydonfilmoffice.co.uk/2016/07/15/the-heart-of-the-action-croydons-getting-a-reputation-for-attracting-blockbusters/","https://www.yourlocalguardian.co.uk/news/14410419.revealed-croydons-role-in-the-blockbuster-criminal-starring-kevin-costner-and-ryan-reynolds/"],confidence="high",confidence_note="Several sources agree. The KML pin is between the two buildings."),
dict(id="fairfield-halls",name="Fairfield Halls",address="Park Lane, CR9 1DG",lat=51.37282,lng=-0.09685,
 films=[dict(title="The Da Vinci Code",year=2006,type="film",scene="Fairfield's Concert Hall plays the lecture hall where Robert Langdon (Tom Hanks) gives his talk on symbols."),
        dict(title="Cuban Fury",year=2014,type="film",scene="The flashbacks and the salsa competition in the final scene.")],
 image=img("Fairfield Halls - London.jpg","Jim Linwood via Wikimedia Commons","CC BY 2.0"),
 sources=["https://www.yourlocalguardian.co.uk/news/24902765.18-movies-might-not-know-filmed-croydon/","https://www.london-now.co.uk/news/24085156.9-movies-filmed-croydon-might-not-realise/","Croydonites Crollywood 2026 listing (mentions The Da Vinci Code)"],confidence="high",confidence_note="Not on the KML map, but backed by several press sources and the 2026 tour blurb."),
dict(id="made-in-dagenham",name="Park Lane / Fairfield forecourt",address="Park Lane, CR0",lat=51.37320,lng=-0.09776,
 films=[dict(title="Made in Dagenham",year=2010,type="film",scene="Croydon's 1960s concrete stands in for 1968 Westminster and Dagenham. Scenes were shot on St George's Walk and at Fairfield Halls.")],
 image=img("Fairfield Hall, Croydon - geograph.org.uk - 2819880.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=[KML,"https://www.yourlocalguardian.co.uk/news/24902765.18-movies-might-not-know-filmed-croydon/"],confidence="medium",confidence_note="The map pin has no description, and the scene details are generic."),
dict(id="heads-of-state-sgw",name="St George's Walk (the 'Warsaw' street)",address="St George's Walk, CR0 1PB",lat=51.37321,lng=-0.09857,
 films=[dict(title="Heads of State",year=2025,type="film",scene="On 20–21 June 2023 the arcade was dressed overnight as a Polish high street, with a nightclub, Polish shopfronts, posters and graffiti, for the Warsaw chase with Idris Elba, John Cena and Priyanka Chopra Jonas. Richard's Heads of State: Redux recreates these scenes.")],
 image=img("St George's Walk (1) - geograph.org.uk - 2631951.jpg","geograph.org.uk contributor via Wikimedia Commons","CC BY-SA 2.0"),
 sources=["https://www.mylondon.news/news/south-london-news/idris-elba-john-cena-priyanka-27170859","https://insidecroydon.com/2023/06/22/idris-elba-and-film-co-stars-spotted-doing-the-st-georges-walk/","https://www.croydonites.com/programme/redux-heads-of-state"],confidence="high",confidence_note="Several press sources, plus Croydonites saying the Warsaw chase was filmed in the town centre. The exact frame-by-frame spots are for Richard to refine."),
dict(id="american-assassin",name="St George's Walk (Park Street end)",address="St George's Walk, CR0 1YJ",lat=51.37290,lng=-0.09851,
 films=[dict(title="American Assassin",year=2017,type="film",scene="St George's Walk is transformed into an Istanbul quarter for Michael Keaton and Dylan O'Brien. This is the subject of Richard's 2018 American Assassin: Redux."),
        dict(title="Black Mirror: Bandersnatch",year=2018,type="TV/interactive film",scene="Retro 1984 shopfronts, including the Tuckersoft-era high street, were fitted on the now-demolished half of the Walk.")],
 image=img("St. George's Walk 2015.JPG","Eagleash via Wikimedia Commons","CC BY-SA 4.0"),
 sources=[KML,"https://www.copsecroydon.co.uk/event/local-evening-walk-no-hall/","https://www.mylondon.news/news/south-london-news/idris-elba-john-cena-priyanka-27170859"],confidence="high",confidence_note="Map pins for both titles are about 15m apart. Bandersnatch's half of the Walk has been demolished."),
dict(id="the-bill",name="Katharine Street / Park Street corner",address="Katharine Street, CR0",lat=51.37299,lng=-0.09948,
 films=[dict(title="The Bill",year=1984,type="TV",scene="The long-running police drama often filmed in central Croydon, around Surrey Street and St George's House (the Nestlé Building).")],
 image=None,
 sources=[KML,"https://en-academic.com/dic.nsf/enwiki/273044"],confidence="low",confidence_note="Map pin has no description, so the specific episode or scene is unknown."),
]
for i,s in enumerate(S):
    s["order"]=i+1
    s["clip"]=f"media/clips/{s['id']}.mp4"
    s["audio"]=f"media/audio/{s['id']}.mp3"
out={"title":"Crollywood","subtitle":"A self-guided walk through Croydon's movie locations","artist":"Richard DeDomenici / The Redux Project",
 "loop":"Starts and ends at the David Lean Cinema (stop 1). The route line is drawn as straight segments between stops, so follow the footpaths.",
 "dropped":[{"name":"Brazil (1985)","reason":"Map pin at 51.3805,-0.1229 is about 1.6km west of the loop (Purley Way side), outside the walkable town-centre radius.","source":KML}],
 "stops":S}
json.dump(out,open("locations.json","w"),indent=2,ensure_ascii=False)
print(len(S))
